version: '3.8'

services:
  web:
    build: ./beneighb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./beneighb/:/usr/src/beneighb/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
