version: '3.8'

services:
  web:
    image: ghcr.io/beneighb/backend/web:latest
    build:
      context: ./beneighb
      dockerfile: Dockerfile.prod
    command: gunicorn beneighb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/beneighb/web/staticfiles
      - media_volume:/home/beneighb/web/mediafiles
    expose:
        - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: ghcr.io/beneighb/backend/postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: ghcr.io/beneighb/backend/nginx:latest
    build: ./nginx
    volumes:
      - static_volume:/home/beneighb/web/staticfiles
      - media_volume:/home/beneighb/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
