version: '3.8'

services:
  web:
    platform: linux/amd64
    image: ghcr.io/beneighb/backend/web
    restart: always
    command: gunicorn beneighb.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-'
    volumes:
      - static_volume:/home/beneighb/web/staticfiles
      - media_volume:/home/beneighb/web/mediafiles
      # - gunicorn_logs:/home/beneighb/web/logs
      - ./data/fcm:/home/beneighb/web/fcm  # For FCM credentials file
    ports:
      - 587:587
    expose:
      - 8000
      - 587
    env_file:
      - ./.env.prod
    environment:
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: ghcr.io/beneighb/backend/postgres
    platform: linux/amd64
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  backup:
    restart: unless-stopped
    image: python:3.12.0b3-alpine3.18
    command: |
      sh -c "while :; echo 'HEEEEEELLLLLL YEAAAAAAH'; sleep 60; done"
    # volumes:
      # - ./backup_db.sh:/app/backup_db.sh
      # - ./data/backups:/backups
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    depends_on:
      - db


  nginx:
    platform: linux/amd64
    image: ghcr.io/beneighb/backend/nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/home/beneighb/web/staticfiles
      - media_volume:/home/beneighb/web/mediafiles
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  redis:
      restart: unless-stopped
      image: redis:latest
      expose:
          - 6379

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static_volume:
  media_volume:
  # gunicorn_logs:
