version: '3.8'

services:
  web:
    build:
      context: ./beneighb
      dockerfile: Dockerfile.prod
    command: gunicorn beneighb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - web

volumes:
  postgres_data:
