version: '3.8'

services:
  web:
    platform: linux/amd64
    build:
      context: ./beneighb
      dockerfile: Dockerfile
    # restart: always
    # command: gunicorn beneighb.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/beneighb/web/staticfiles
      - media_volume:/home/beneighb/web/mediafiles
    ports:
      - 587:587
      - 8000:8000
    expose:
      - 8000
      - 587
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: ghcr.io/beneighb/backend/postgres
    platform: linux/amd64
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      # TODO: Create .env.dev.db
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume:
