version: '3.8'

services:
  web:
    build: ./beneighb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./beneighb/:/usr/src/beneighb/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=beneighb
      - POSTGRES_PASSWORD=beneighb
      - POSTGRES_DB=beneighb
volumes:
  postgres_data:
