export DEBUG=1
export SECRET_KEY="foo"
export DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1"
# export SQL_ENGINE=django.db.backends.postgresql
# export SQL_DATABASE=beneighb
# export SQL_USER=beneighb
# export SQL_PASSWORD=beneighb
# export SQL_HOST=db
# export SQL_PORT=5432
# export DATABASE=postgres
