# Generated by Django 4.2.2 on 2023-10-26 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_subcategories"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubCategory",
            new_name="Service",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="ServiceCategory",
        ),
    ]
