# Generated by Django 4.2.2 on 2023-10-26 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_rename_subcategory_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
    ]
