# Generated by Django 4.2.2 on 2023-10-28 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_alter_service_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={"verbose_name_plural": "Service Categories"},
        ),
    ]
