# Generated by Django 4.2.2 on 2023-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0005_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
