# Generated by Django 4.2.2 on 2023-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0009_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
