# Generated by Django 4.2.2 on 2023-12-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0010_offer_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")], max_length=9
            ),
        ),
    ]
