# Generated by Django 4.2.2 on 2024-01-04 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0011_assignment_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
