# Generated by Django 4.2.2 on 2023-12-29 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0011_alter_offer_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="is_accepted",
        ),
    ]
