# Generated by Django 4.2.2 on 2024-04-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0012_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='marketplace.task',
            ),
        ),
    ]
