# Generated by Django 4.2.2 on 2024-04-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0013_alter_offer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='marketplace.task',
            ),
        ),
    ]
