# Generated by Django 4.2.2 on 2024-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0014_alter_offer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='info',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
