# Generated by Django 4.2.2 on 2024-07-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_block'),
        ('marketplace', '0015_task_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='helper',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='users.profile',
            ),
        ),
        migrations.AlterField(
            model_name='offer',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='marketplace.task',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='users.profile',
            ),
        ),
    ]
