# Generated by Django 4.2.2 on 2023-10-03 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="speaking_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("eo", "Esperanto"),
                        ("uk", "Ukrainian"),
                        ("en", "English"),
                        ("ar", "Arabic"),
                        ("fr", "French"),
                        ("es", "Spanish"),
                        ("de", "German"),
                        ("it", "Italian"),
                        ("zh", "Chinese"),
                        ("ja", "Japanese"),
                        ("ko", "Korean"),
                        ("pt", "Portuguese"),
                        ("tr", "Turkish"),
                        ("pl", "Polish"),
                        ("ru", "Russian"),
                    ],
                    max_length=2,
                ),
                default=["en"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
