# Generated by Django 4.2.2 on 2023-10-12 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_speaking_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="speaking_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("af", "Afrikaans"),
                        ("ar", "Arabic"),
                        ("hy", "Armenian"),
                        ("bn", "Bengali"),
                        ("bg", "Bulgarian"),
                        ("zh", "Chinese"),
                        ("hr", "Croatian"),
                        ("cs", "Czech"),
                        ("da", "Danish"),
                        ("nl", "Dutch"),
                        ("en", "English"),
                        ("et", "Estonian"),
                        ("eo", "Esperanto"),
                        ("fa", "Farsi"),
                        ("fi", "Finnish"),
                        ("fr", "French"),
                        ("ka", "Georgian"),
                        ("de", "German"),
                        ("el", "Greek"),
                        ("hi", "Hindi"),
                        ("hu", "Hungarian"),
                        ("id", "Indonesian"),
                        ("it", "Italian"),
                        ("ja", "Japanese"),
                        ("kk", "Kazakh"),
                        ("ko", "Korean"),
                        ("ku", "Kurdish"),
                        ("mk", "Macedonian"),
                        ("no", "Norwegian"),
                        ("pl", "Polish"),
                        ("pt", "Portuguese"),
                        ("ro", "Romanian"),
                        ("ru", "Russian"),
                        ("sk", "Slovak"),
                        ("sl", "Slovenian"),
                        ("es", "Spanish"),
                        ("sv", "Swedish"),
                        ("th", "Thai"),
                        ("tr", "Turkish"),
                        ("uk", "Ukrainian"),
                        ("ur", "Urdu"),
                        ("uz", "Uzbek"),
                        ("vi", "Vietnamese"),
                    ],
                    max_length=2,
                ),
                size=None,
            ),
        ),
    ]
