# Generated by Django 4.2.2 on 2023-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
        ("users", "0004_alter_profile_speaking_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="subcategories", to="marketplace.subcategory"
            ),
        ),
    ]
