# Generated by Django 4.2.2 on 2023-10-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
        ("users", "0005_profile_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="subcategories", to="marketplace.subcategory"
            ),
        ),
    ]
