# Generated by Django 4.2.2 on 2023-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0004_alter_servicecategory_options"),
        ("users", "0006_alter_profile_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="profile",
            name="services",
            field=models.ManyToManyField(blank=True, to="marketplace.service"),
        ),
    ]
