# Generated by Django 4.2.2 on 2024-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_profile_subcategories_profile_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
