# Generated by Django 4.2.2 on 2024-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(
                choices=[('Dusseldorf', 'Dusseldorf'), ('Berlin', 'Berlin')],
                default='Dusseldorf',
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
