# Generated by Django 4.2.2 on 2024-07-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'blocked_profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked_profile',
                        to='users.profile',
                    ),
                ),
                (
                    'blocking_profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocking_profile',
                        to='users.profile',
                    ),
                ),
            ],
            options={
                'unique_together': {('blocked_profile', 'blocking_profile')},
            },
        ),
    ]
