# Generated by Django 4.2.2 on 2024-07-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'blocked',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked',
                        to='users.profile',
                    ),
                ),
                (
                    'blocked_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='blocked_by',
                        to='users.profile',
                    ),
                ),
            ],
        ),
    ]
