# Generated by Django 4.2.2 on 2024-01-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_profile_fcm_token"),
        ("chat", "0003_alter_message_read_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="author",
            new_name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
