# Generated by Django 4.2.2 on 2024-04-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0012_delete_chat'),
        ('chat', '0004_rename_author_message_sender_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='assignment',
        ),
        migrations.AddField(
            model_name='chat',
            name='offer',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='marketplace.offer',
            ),
        ),
    ]
