# Generated by Django 4.2.2 on 2024-04-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('marketplace', '0012_delete_chat'),
        ('chat', '0006_migrate_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='offer',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='marketplace.offer',
            ),
            preserve_default=False,
        ),
    ]
